# Generated by Django 3.2.16 on 2023-02-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('name', models.CharField(max_length=90, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('name', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('courses', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='homework_s',
            fields=[
                ('addresses', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('descriptions', models.CharField(max_length=200)),
                ('homework_file', models.FileField(upload_to='home_work_files/')),
                ('Date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='message_data',
            fields=[
                ('receiver', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=90)),
                ('content', models.TextField()),
            ],
        ),
    ]
