# Generated by Django 3.2.16 on 2023-02-24 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_data',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.user_data'),
        ),
        migrations.AddField(
            model_name='homework_s',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.user_data'),
        ),
        migrations.AddField(
            model_name='friends',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.user_data'),
        ),
    ]
