# Generated by Django 3.2.16 on 2023-02-24 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('title', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('lesson_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers_message',
            fields=[
                ('receiver', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=90)),
                ('content', models.TextField()),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.user_data')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers_homework',
            fields=[
                ('homework_title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('homework_description', models.CharField(max_length=200)),
                ('first_question', models.CharField(max_length=110)),
                ('secound_question', models.CharField(max_length=110)),
                ('third_question', models.CharField(max_length=110)),
                ('fourth_question', models.CharField(max_length=110)),
                ('fifth_question', models.CharField(max_length=110)),
                ('form_type', models.CharField(choices=[('form1', 'form-type1'), ('form2', 'form-type2'), ('form3', 'form-type3'), ('form4', 'form-type4'), ('form5', 'form-type5')], max_length=7)),
                ('font_size', models.CharField(choices=[('font-size1', '10%'), ('font-size2', '20%'), ('font-size3', '40%'), ('font-size4', '60%'), ('font-size5', '80%'), ('font-size6', '100%')], max_length=20)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.user_data')),
            ],
        ),
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('content', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now=True)),
                ('hora_post', models.TimeField(auto_now=True)),
                ('post_img', models.ImageField(upload_to='TComentImg/')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.user_data')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courses_name', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('courses_description', models.CharField(max_length=300)),
                ('miniatura', models.ImageField(upload_to='')),
                ('hora_ini', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.user_data')),
            ],
        ),
    ]
